apiVersion: apps/v1
kind: Deployment
metadata:
  name: ml-model-deployment
  labels:
    app: ml-model
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ml-model
  template:
    metadata:
      labels:
        app: ml-model
      annotations:
        prometheus.io/scrape: "true"       # Enable Prometheus scraping
        prometheus.io/path: "/metrics"    # Metrics endpoint
        prometheus.io/port: "5000"        # Port for metrics scraping
    spec:
      containers:
        - name: ml-model
          image: acrterraformsepsisstreamingv1.azurecr.io/your-image-name:latest
          ports:
            - containerPort: 5000
          env:
            - name: ENV
              value: "production" # Optional: Set environment variables
