name: CI/CD for Model Deployment with AKS and ACR

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout Repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Step 2: Authenticate with Azure CLI
      - name: Authenticate with Azure CLI
        run: az login --use-device-code

      # Step 3: Attach ACR to AKS
      - name: Attach ACR to AKS
        run: |
          az aks update \
            --resource-group rg-aks-acr-terraform \
            --name aks-terraform-cluster \
            --attach-acr acrterraformSepsisStreaming

      # Step 4: Build Docker Image (Commented Out)
      # - name: Build Docker Image
      #   run: |
      #     az acr login --name acrterraformSepsisStreaming
      #     docker build -t acrterraformsepsisstreaming.azurecr.io/randomforest:staging .
      #     docker push acrterraformsepsisstreaming.azurecr.io/randomforest:staging

      # Step 5: Configure kubectl for AKS
      - name: Configure kubectl
        run: |
          az aks get-credentials \
            --resource-group rg-aks-acr-terraform \
            --name aks-terraform-cluster \
            --overwrite-existing

      # Step 6: Deploy Application to AKS
      - name: Deploy Application
        run: |
          kubectl apply -f k8s/deployment.yaml
          kubectl apply -f k8s/service.yaml
