name: CI/CD for Model Deployment with Event Hub

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout Repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Step 2: Authenticate with Azure CLI
      - name: Authenticate with Azure CLI
        run: az login --use-device-code

      # Step 3: Run Model Tests
      - name: Run Model Tests
        run: |
          pip install pytest mlflow pandas
          pytest tests/

      # Step 4: Build Docker Image
      - name: Build Docker Image
        run: |
          docker build -t acrterraformsepsisstreaming.azurecr.io/randomforest:staging .

      # Step 5: Login to ACR using Admin Credentials
      - name: Login to ACR
        run: |
          docker login acrterraformsepsisstreaming.azurecr.io \
            -u "acrterraformSepsisStreaming" \
            -p "PQ3Te9RolGBeaiwpouUmh0BFCQSSB0ECqFKHegFJub+ACRCH/KKk"

      # Step 6: Push Docker Image to ACR
      - name: Push Docker Image to ACR
        run: |
          docker push acrterraformsepsisstreaming.azurecr.io/randomforest:staging

      # Step 7: Deploy to AKS
      - name: Deploy to AKS
        run: |
          kubectl apply -f k8s/deployment.yaml
          kubectl apply -f k8s/service.yaml
