name: CI/CD for Model Deployment with Event Hub

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout Repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Step 4: Authenticate with Azure CLI
      - name: Authenticate with Azure CLI
        run: az login --use-device-code

      # Step 6: Build Docker Image
      - name: Build Docker Image
        run: |
          docker build -t acrterraformSepsisStreaming.azurecr.io/randomforest:staging .

      # Step 7: Push Docker Image to ACR
      - name: Push Docker Image to ACR
        run: |
          az acr login --name acrterraformSepsisStreaming
          docker push acrterraformSepsisStreaming.azurecr.io/randomforest:staging

      # Step 8: Deploy to AKS
      - name: Deploy to AKS
        run: |
          kubectl apply -f k8s/deployment.yaml
          kubectl apply -f k8s/service.yaml
