name: Build and Deploy to ACR

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    name: Build and Deploy Docker Image to ACR
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 2: Authenticate with Azure CLI using Device Code
      - name: Authenticate with Azure CLI
        run: az login --use-device-code

      # Step 3: Set Azure Subscription
      - name: Set Azure Subscription
        run: az account set --subscription "1fad5e2e-cd4b-437b-8fff-ee503b4e0e29"

      # Step 4: Log in to Azure Container Registry
      - name: Log in to Azure Container Registry
        run: az acr login --name acrterraformSepsisStreaming

      # Step 5: Build and Push Docker Image
      - name: Build and Push Docker Image
        run: |
          docker build -t acrterraformsepsisstreaming.azurecr.io/your-image-name:latest .
          docker push acrterraformsepsisstreaming.azurecr.io/your-image-name:latest
