name: CI/CD for Model Deployment with Event Hub

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout Repository
      - name: Checkout Repository
        uses: actions/checkout@v3



      # Step 3: Set Up Python Environment
      - name: Set Up Python Environment
        run: |
          python3 -m venv .venv
          source .venv/bin/activate
          pip install --upgrade pip
          pip install mlflow==2.19.0 cloudpickle==3.1.0 scikit-learn==1.0.2 pytest pandas

      # Step 4: Run Model Tests
      - name: Run Model Tests
        run: |
          source .venv/bin/activate
          pytest tests/

      # Step 5: Build Docker Image
      - name: Build Docker Image
        run: |
          docker build -t acrterraformSepsisStreaming.azurecr.io/randomforest:staging .

      # Step 6: Push Docker Image to ACR
      - name: Push Docker Image to ACR
        run: |
          az acr login --name acrterraformSepsisStreaming
          docker push acrterraformSepsisStreaming.azurecr.io/randomforest:staging

      # Step 7: Deploy to AKS
      - name: Deploy to AKS
        run: |
          kubectl apply -f k8s/deployment.yaml
          kubectl apply -f k8s/service.yaml
