name: CI/CD for Model Deployment with Event Hub

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout Repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Step 2: Set up Python Environment
      - name: Set up Python 3.11 (Compatible with dependencies)
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      # Step 3: Upgrade Build Tools
      - name: Upgrade pip, setuptools, and wheel
        run: |
          python -m pip install --upgrade pip setuptools wheel

      # Step 4: Install Specific Dependencies
      - name: Install Dependencies
        run: |
          pip install cython==0.29.33
          pip install scikit-learn==1.0.2
          pip install mlflow==2.19.0 pandas pytest

      # Step 5: Run Model Tests
      - name: Run Model Tests
        run: |
          pytest tests/

      # Step 6: Build Docker Image
      - name: Build Docker Image
        run: |
          docker build -t acrterraformSepsisStreaming.azurecr.io/randomforest:staging .

      # Step 7: Push Docker Image to ACR
      - name: Push Docker Image to ACR
        run: |
          az acr login --name acrterraformSepsisStreaming
          docker push acrterraformSepsisStreaming.azurecr.io/randomforest:staging

      # Step 8: Deploy to AKS
      - name: Deploy to AKS
        run: |
          kubectl apply -f k8s/deployment.yaml
          kubectl apply -f k8s/service.yaml
